version: "3.1"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: issue-tracker
    ports:
      - 5432:5432
    volumes:
      - db-data-postgresql:/var/lib/postgresql/data

volumes:
  db-data-postgresql:
